<a href="https://colab.research.google.com/github/entangelk/study_data_analytics/blob/main/docs/quests/DDA/quest_spinesurgery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [17]:
pd.set_option('display.max_columns', None)

In [2]:
sslist = pd.read_csv('SpineSurgeryList.csv')

In [3]:
sslist.columns

Index(['Unnamed: 0', '환자ID', 'Large Lymphocyte', 'Location of herniation',
       'ODI', '가족력', '간질성폐질환', '고혈압여부', '과거수술횟수', '당뇨여부', '말초동맥질환여부', '빈혈여부',
       '성별', '스테로이드치료', '신부전여부', '신장', '심혈관질환', '암발병여부', '연령', '우울증여부', '입원기간',
       '입원일자', '종양진행여부', '직업', '체중', '퇴원일자', '헤모글로빈수치', '혈전합병증여부', '환자통증정도',
       '흡연여부', '통증기간(월)', '수술기법', '수술시간', '수술실패여부', '수술일자', '재발여부', '혈액형',
       '전방디스크높이(mm)', '후방디스크높이(mm)', '지방축적도', 'Instability', 'MF + ES',
       'Modic change', 'PI', 'PT', 'Seg Angle(raw)', 'Vaccum disc', '골밀도',
       '디스크단면적', '디스크위치', '척추이동척도', '척추전방위증'],
      dtype='object')

In [4]:
sslist

,Unnamed: 0,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,...,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
0,0,1PT,22.8,3,51.0,0.0,0,0,0,0,...,3,51.6,36.6,14.4,0,-1.01,2048.50,4,Down,0
1,1,2PT,44.9,4,26.0,0.0,0,0,0,0,...,0,40.8,7.2,17.8,0,-1.14,1753.10,4,Up,0
2,2,3PT,53.0,3,NaN,0.0,0,0,1,0,...,0,67.5,27.3,10.2,0,-1.77,1749.00,4,Down,0
3,3,4PT,54.7,4,18.0,0.0,0,1,0,0,...,0,49.2,18.7,19.9,0,-1.58,1796.20,4,Down,0
4,4,5PT,53.8,4,NaN,0.0,0,1,0,0,...,0,58.8,14.7,5.2,0,-0.79,2021.48,4,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1889,1889,1890PT,44.0,1,NaN,0.0,0,0,0,0,...,2,59.5,23.0,21.8,0,NaN,2652.20,5,Middle,0
1890,1890,1891PT,30.8,2,NaN,0.0,0,0,0,0,...,0,47.7,20.2,5.0,0,NaN,1795.80,4,Down,0
1891,1891,1892PT,36.7,3,NaN,0.0,0,0,0,0,...,0,44.6,15.0,17.4,1,NaN,2624.40,4,Down,0
1892,1892,1893PT,32.5,2,NaN,0.0,0,0,0,0,...,2,32.2,11.1,17.7,0,NaN,1972.50,5,Down,0
1893,1893,1894PT,49.5,2,NaN,0.0,0,0,0,0,...,0,38.9,6.8,27.8,0,NaN,1574.40,5,Middle,0

In [18]:
sslist.describe(include='all')

,Unnamed: 0,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,말초동맥질환여부,빈혈여부,성별,스테로이드치료,신부전여부,신장,심혈관질환,암발병여부,연령,우울증여부,입원기간,입원일자,종양진행여부,직업,체중,퇴원일자,헤모글로빈수치,혈전합병증여부,환자통증정도,흡연여부,통증기간(월),수술기법,수술시간,수술실패여부,수술일자,재발여부,혈액형,전방디스크높이(mm),후방디스크높이(mm),지방축적도,Instability,MF + ES,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
count,1894.000000,1894,1894.000000,1894.000000,462.000000,1843.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1.894000e+03,1894.000000,1479,1894.000000,1.894000e+03,1893.00000,1894.000000,1894.000000,1894.000000,1890.000000,1813,1840.000000,1894.000000,1.894000e+03,1894.000000,1894,1894.000000,1894.000000,1891.000000,1894.000000,1894.000000,1894.000000,1890.000000,1890.000000,1893.000000,1894.000000,998.000000,1893.000000,1894.000000,1894,1894.000000
unique,NaN,1894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN
top,NaN,1PT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,사무직,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TELD,NaN,NaN,NaN,NaN,RH+A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Middle,NaN
freq,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1673,NaN,NaN,NaN,NaN,688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1260,NaN
mean,946.500000,NaN,39.270750,2.295671,31.142857,0.049919,0.020063,0.130940,0.302534,0.062830,0.004224,0.024287,1.383316,0.598733,0.025343,168.027983,0.035903,0.013728,41.463569,0.023231,1.736536,2.016015e+07,0.003168,NaN,68.111140,2.016000e+07,14.58113,0.002112,6.884372,0.217001,5.879841,NaN,62.066304,0.060718,2.016023e+07,0.119852,NaN,11.382635,8.358126,241.524289,0.040655,2096.421600,0.247096,46.593651,16.329841,15.287934,0.056494,-1.507325,1989.788774,4.430834,NaN,0.032207
std,546.895023,NaN,13.675874,0.996143,10.131304,0.217836,0.140254,0.337424,0.638461,0.242721,0.064871,0.153980,0.486323,0.490284,0.157207,9.211419,0.186097,0.116388,13.444629,0.154143,2.344085,3.677496e+04,0.056210,NaN,11.234318,3.689652e+04,1.55126,0.045919,2.075907,0.412312,17.241970,NaN,24.994615,0.238875,3.682868e+04,0.324874,NaN,2.852451,4.244340,445.211922,0.197541,472.834488,0.661506,22.736211,8.421322,10.426397,0.230935,0.495867,314.478436,3.595680,NaN,0.176596
min,0.000000,NaN,0.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,140.000000,0.000000,0.000000,15.000000,0.000000,0.000000,2.009012e+07,0.000000,NaN,35.000000,2.009012e+07,7.00000,0.000000,1.000000,0.000000,0.000000,NaN,5.000000,0.000000,2.009012e+07,0.000000,NaN,1.270000,1.000000,25.970000,0.000000,1016.800000,0.000000,11.900000,-10.600000,-27.400000,0.000000,-2.840000,1145.800000,1.000000,NaN,0.000000
25%,473.250000,NaN,30.700000,1.000000,24.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,161.000000,0.000000,0.000000,32.000000,0.000000,1.000000,2.012111e+07,0.000000,NaN,59.700000,2.012101e+07,13.50000,0.000000,7.000000,0.000000,1.000000,NaN,45.000000,0.000000,2.012111e+07,0.000000,NaN,9.540000,7.100000,121.145000,0.000000,1765.285000,0.000000,38.700000,10.500000,8.800000,0.000000,-1.820000,1777.000000,4.000000,NaN,0.000000
50%,946.500000,NaN,40.200000,2.000000,31.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,169.000000,0.000000,0.000000,41.000000,0.000000,1.000000,2.018123e+07,0.000000,NaN,68.000000,2.019010e+07,14.65000,0.000000,7.000000,0.000000,2.000000,NaN,60.000000,0.000000,2.019010e+07,0.000000,NaN,11.200000,8.300000,169.100000,0.000000,2056.500000,0.000000,45.100000,15.700000,14.500000,0.000000,-1.520000,1985.500000,4.000000,NaN,0.000000
75%,1419.750000,NaN,48.600000,3.000000,38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,175.000000,0.000000,0.000000,49.000000,0.000000,2.000000,2.019062e+07,0.000000,NaN,75.000000,2.019062e+07,15.64000,0.000000,8.000000,0.000000,4.000000,NaN,77.000000,0.000000,2.019062e+07,0.000000,NaN,13.200000,9.500000,251.800000,0.000000,2374.350000,0.000000,52.000000,21.400000,21.100000,0.000000,-1.202500,2178.500000,4.000000,NaN,0.000000
max,1893.000000,NaN,89.000000,5.000000,68.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,204.000000,1.000000,1.000000,86.000000,2.000000,51.000000,2.020080e+07,1.000000,NaN,136.100000,2.020081e+07,19.38000,1.000000,10.000000,1.000000,360.000000,NaN,220.000000,1.000000,2.020081e+07,1.000000,NaN,22.500000,101.000000,12113.470000,1.000000,5569.000000,3.000000,559.000000,48.700000,165.000000,1.000000,1.700000,3214.200000,45.000000,NaN,1.000000

In [ ]:
sslist['Large Lymphocyte'].unique()

In [ ]:
sslist['Location of herniation'].unique()

In [ ]:
sslist['ODI'].unique()

In [ ]:
sslist['가족력'].unique()

In [ ]:
sslist['과거수술횟수'].unique()

In [ ]:
sslist['당뇨여부'].unique()

In [ ]:
sslist['직업'].unique()

In [ ]:
sslist['수술기법'].unique()

In [21]:
sslist['혈액형'].unique()

array(['RH+A', 'RH+B', 'RH+O', 'RH+AB'], dtype=object)

In [23]:
sslist['Modic change'].unique()

array([3, 0, 2, 1])

In [25]:
sslist['척추이동척도'].unique()

array(['Down', 'Up', 'Middle', 'Extremely down', 'Extremely up'],
      dtype=object)